### ISSUE TITLE
Leiden Clustering implementation

### ISSUE THREAD

**Issue by narendrachaudhary51** [KatanaGraph/katana#186]
Following from issue https://github.com/KatanaGraph/katana/issues/70
I saw that in previous version of Galois ("git clone https://github.com/IntelligentSoftwareSystems/Galois"), there is an implementation of leiden clustering under clustering folder (Galois/lonestar/analytics/cpu/clustering). Why was this removed in the latest version? Can you please add it again?

Last commit with leiden clustering in message. 

commit ce78fe5807e08ce1e22684ee12ee8ad734da6c0f
Author: Udit Agarwal <udit@cs.utexas.edu>
Date:   Tue Apr 28 13:55:32 2020 -0500

    corrected the implementation of leiden clustering

**Comment by arthurp** [comment]
We are unlikely to have time for this for a bit, but we'll take a look at it when we have time.

**Comment by narendrachaudhary51** [comment]
Hi @arthurp,
Additionally, the binaries do not seem to provide any partition output. Other louvain and leiden algorithm (from different python packages) implementations seem to provide graph partitions. Is it available in the newer binaries of the Louvain algorithm? What I should do to obtain graph partitions if they are not available with binaries?

**Comment by arthurp** [comment]
The clusters are represented as a new property containing integer cluster IDs. Is this not acceptable for your use case? Do you want a new graph for each cluster? We could add a separate operation which partitions a graph based on a property (as created by the clustering algorithms). If that would be helpful, please file a separate issue. It's a good idea I think. Though it may not be applicable to large graphs (millions of nodes) because there could be a huge number of clusters and the operation could consume too much memory to be useful.

**Comment by narendrachaudhary51** [comment]
I didn't understand the purpose of --output_CID option earlier. I may be able to work with it. Thank you for mentioning it.

**Comment by GioLomia** [comment]
Shouldn't this be closed considering #544 ?

**Comment by uditagar** [comment]
Implemented now
