### ISSUE TITLE
Create an in memory only `Copy` operation on `PropertyFileGraph`

### ISSUE THREAD

**Issue by arthurp** [KatanaGraph/katana#38]
#31 adds a [`Copy` operation to `PropertyFileGraph`](https://github.com/KatanaGraph/katana/pull/31/files#diff-d0a90bcf8c90f4637fccdcc12945ad83f5bd09c42663c9f2179a9d96ff11e581). It reloads the graph from storage instead of doing an in-memory copy. This has two potential issues:

* It's probably slower.
* The copy can be saved out to storage replacing the original.

For truly ephemeral copies (that are only used during the execution of one algorithm), these are not ideal. And there is no advantage of having any real fault tolerance on ephemeral copy, so storage backing isn't needed.

**Comment by ddn0** [comment]
Let me refine my argument :D 

In general, we are aiming to support workflows of creating, modifying and merging graphs. The storage representation is designed to checkpoint and distribute data between workflows and routines. For overall economy of mechanism, I'd much rather have these ephemeral use-cases treated as an instance of a general mechanism rather than doing extensive work to optimize the special case, especially when we don't have the general workflow mapped out.

I don't have a problem with in-memory copy in principle, but if we are already considering going to storage a moderate to huge inconvenience, it might make sense to step back and make sure we are still comfortable with the overall design.

Also, things like `TemporaryPropertyGuard` 
https://github.com/KatanaGraph/katana/pull/31/files#diff-8e6f8f03ea820e0b8b11b6d6c7784a66b8a87e271f433571356af91a26e5a25bR73
make me wonder if we have the right API now.

**Comment by arthurp** [comment]
> Also, things like `TemporaryPropertyGuard`
> https://github.com/KatanaGraph/katana/pull/31/files#diff-8e6f8f03ea820e0b8b11b6d6c7784a66b8a87e271f433571356af91a26e5a25bR73
> make me wonder if we have the right API now.

Can you expand on this? Are you implying that a way to create RDG properties that are natively ephemeral and are automatically deleted later might be better? Or that we should have a way to create and access "properties" that are never actually attached to the RDG and are only local objects? These two approaches also have interestingly different extensions to distributed (one gives potential sharing but makes allocating them more expensive, the other makes the ephemeral property node local but faster to allocate).

**Comment by ddn0** [comment]
In general, I'd like to get to a point where there is a clear and reasonably encapsulated division of responsibility between the compute and storage layers. My working model has been that the storage layer should be largely in charge of "virtualization of data" (i.e., giving the appearance of infinite-capacity, fast storage regardless of physical restrictions) and "consistency" with compromises to reflect common use-cases, storage restrictions, etc.

Having logic in the compute layer that implements certain policies which overlap with this responsibility might be reasonable in the short-term, but we should bubble this up to see if this is sustainable in the long-term.

Ephemeral properties, in my mind, intersect with both the virtualization and consistency aspects of the storage layer.

Virtualization: whether we actually spill out to backing storage or keep things in memory but maybe replicated seems like something the storage layer is in a better position to decide rather than an individual compute routine.

Consistency: if ephemeral properties are temporary, would the best way to explain their scope be a transaction?

Anyway, I don't think resolving this is urgent because the current use of ephemeral properties is to allocate temporary working memory for "the one and only current graph" and our implicit transaction boundary is a single compute routine, but as we work to compose routines, what is a persistent update for one routine might be an ephemeral update when composed in a larger workflow.

cc @witchel @tylershunt (for the "bubbling up")

**Comment by arthurp** [comment]
Fixed in e89c3228fe77372d09b33ad76d27b36e2928d6d3.

**Comment by witchel** [comment]
Arthur, I love your hobby.  The comedian George Carlin said that saving food makes you feel good twice.  The first time you think, "I'm saving food!"  And then when you throw out the leftovers you think, "I'm saving my life!"

Seeing this issue get closed well after I've forgotten all about it all gives me a feeling of accomplishment that almost never happens in the morning.
